version: '3'
services:
 
    rabbit:
        image: "rabbitmq:3-management"
        environment: 
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            # port to access rabbitmq ui
            - "15672:15672"
            # port to internal apps access
            - "5672:5672"